"""settlement_revenue_tax_models

Revision ID: 9c75dc80485b
Revises: db_optimization_indexes
Create Date: 2026-06-22 11:52:11.856139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c75dc80485b'
down_revision: Union[str, Sequence[str], None] = 'db_optimization_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_feed_user_id_type'), table_name='activity_feed')
    op.drop_index(op.f('ix_audit_logs_action_created'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_address'), table_name='audit_logs')
    op.drop_index(op.f('ix_countries_service_id_provider'), table_name='countries')
    op.drop_index(op.f('ix_invoices_user_id_status'), table_name='invoices')
    op.drop_index(op.f('ix_ledger_entries_user_id_currency'), table_name='ledger_entries')
    op.drop_index(op.f('ix_notifications_user_id_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_number_rentals_expires_at_status'), table_name='number_rentals')
    op.drop_index(op.f('ix_number_rentals_user_id_status'), table_name='number_rentals')
    op.drop_index(op.f('ix_payment_logs_created_at_status'), table_name='payment_logs')
    op.drop_index(op.f('ix_payment_logs_user_id_status'), table_name='payment_logs')
    op.drop_index(op.f('ix_provider_settlements_provider_status'), table_name='provider_settlements')
    op.drop_index(op.f('ix_security_scan_results_status'), table_name='security_scan_results')
    op.drop_index(op.f('ix_sms_orders_created_at_status'), table_name='sms_orders')
    op.drop_index(op.f('ix_sms_orders_provider_status'), table_name='sms_orders')
    op.drop_index(op.f('ix_sms_orders_user_id_status'), table_name='sms_orders')
    op.drop_index(op.f('ix_transactions_created_at_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_id_type'), table_name='transactions')
    op.drop_index(op.f('ix_user_sessions_user_id_active'), table_name='user_sessions')
    op.drop_index(op.f('ix_webhook_events_webhook_id_status'), table_name='webhook_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_webhook_events_webhook_id_status'), 'webhook_events', ['webhook_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id_active'), 'user_sessions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_transactions_user_id_type'), 'transactions', ['user_id', 'type'], unique=False)
    op.create_index(op.f('ix_transactions_created_at_type'), 'transactions', ['created_at', 'type'], unique=False)
    op.create_index(op.f('ix_sms_orders_user_id_status'), 'sms_orders', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_sms_orders_provider_status'), 'sms_orders', ['provider', 'status'], unique=False)
    op.create_index(op.f('ix_sms_orders_created_at_status'), 'sms_orders', ['created_at', 'status'], unique=False)
    op.create_index(op.f('ix_security_scan_results_status'), 'security_scan_results', ['status'], unique=False)
    op.create_index(op.f('ix_provider_settlements_provider_status'), 'provider_settlements', ['provider_name', 'status'], unique=False)
    op.create_index(op.f('ix_payment_logs_user_id_status'), 'payment_logs', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_payment_logs_created_at_status'), 'payment_logs', ['created_at', 'status'], unique=False)
    op.create_index(op.f('ix_number_rentals_user_id_status'), 'number_rentals', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_number_rentals_expires_at_status'), 'number_rentals', ['expires_at', 'status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id_is_read'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_ledger_entries_user_id_currency'), 'ledger_entries', ['user_id', 'currency'], unique=False)
    op.create_index(op.f('ix_invoices_user_id_status'), 'invoices', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_countries_service_id_provider'), 'countries', ['service_id', 'provider'], unique=False)
    op.create_index(op.f('ix_audit_logs_ip_address'), 'audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_created'), 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_feed_user_id_type'), 'activity_feed', ['user_id', 'activity_type'], unique=False)
    # ### end Alembic commands ###
